
version: 0.2

phases:
  test_build:
    commands:
      #Install JAVA 8
     # - add-apt-repository ppa:openjdk-r/ppa
    #  - apt-get update
    #  - apt-get install -y openjdk-8-jdk
    #  - java -version
    
    - mvn test
    
     
  pre_build:
    commands:
      - REPOSITORY_NAME=MishraKD/assin11

  build:
    commands:
      - mvn package
artifacts:
  files:
    - target/Eureka-Server-0.0.1-SNAPSHOT.war
    - Dockerfile
    - build.json
